#!/usr/bin/env python3
# -.- coding: utf-8 -.-
# ktox_loki.py — Loki Autonomous Engine integration for KTOx
#
# Vendors pineapple_pager_loki and runs it headlessly:
#   · webapp at :8000  — full Loki web dashboard & control panel
#   · orchestrator     — autonomous recon / brute-force / exfil loop
#   · no LCD / Pager display required
#
# Data stored in: ktox_loot/loki/
# Loki source:    vendor/loki/  (cloned from pineapple-pager-projects/pineapple_pager_loki)

import os, sys, time, subprocess, threading, socket, signal, shutil
from pathlib import Path

try:
    from rich.console import Console
    from rich.panel   import Panel
    from rich.rule    import Rule
    from rich.table   import Table
    from rich.prompt  import Prompt, Confirm
    from rich         import box
except ImportError:
    print("ERROR: pip3 install rich"); sys.exit(1)

# ── Paths ──────────────────────────────────────────────────────────────────
KTOX_ROOT     = Path(__file__).parent.resolve()
VENDOR_DIR    = KTOX_ROOT / "vendor" / "loki"
LOKI_DIR      = VENDOR_DIR / "payloads" / "user" / "reconnaissance" / "loki"
LOKI_DATA_DIR = KTOX_ROOT / "ktox_loot" / "loki"
LOKI_LAUNCHER = LOKI_DIR / "ktox_headless_loki.py"
LOKI_REPO_URL = "https://github.com/pineapple-pager-projects/pineapple_pager_loki"
LOKI_PORT     = 8000
LOKI_PID_FILE = KTOX_ROOT / "ktox_loot" / "loki.pid"

# ── Palette ────────────────────────────────────────────────────────────────
C_BLOOD  = "#C0392B"
C_RUST   = "#922B21"
C_EMBER  = "#E74C3C"
C_STEEL  = "#717D7E"
C_ASH    = "#ABB2B9"
C_DIM    = "#566573"
C_GOOD   = "#1E8449"
C_ORANGE = "#CA6F1E"

console = Console(highlight=False)

def tag(t, c=C_BLOOD): return f"[{c}]{t}[/{c}]"
def ok(t):   console.print(f"  [{C_GOOD}]✔  {t}[/{C_GOOD}]")
def warn(t): console.print(f"  [{C_ORANGE}]⚠  {t}[/{C_ORANGE}]")
def err(t):  console.print(f"  [{C_BLOOD}]✖  {t}[/{C_BLOOD}]")
def info(t): console.print(f"  [{C_STEEL}]ℹ  {t}[/{C_STEEL}]")

def section(t):
    console.print()
    console.print(Rule(f"[bold {C_BLOOD}] {t} [/bold {C_BLOOD}]", style=C_RUST))
    console.print()

# ── Subprocess state ───────────────────────────────────────────────────────
_loki_proc: subprocess.Popen | None = None
_proc_lock  = threading.Lock()

# ── Helpers ────────────────────────────────────────────────────────────────
def _get_local_ip() -> str:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(2)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "127.0.0.1"

def _loki_installed() -> bool:
    return LOKI_LAUNCHER.exists()

def _loki_running() -> bool:
    global _loki_proc
    with _proc_lock:
        if _loki_proc is not None and _loki_proc.poll() is None:
            return True
        if LOKI_PID_FILE.exists():
            try:
                pid = int(LOKI_PID_FILE.read_text().strip())
                os.kill(pid, 0)
                return True
            except (ProcessLookupError, ValueError, PermissionError):
                LOKI_PID_FILE.unlink(missing_ok=True)
        return False

def _port_in_use(port: int) -> bool:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1)
            return s.connect_ex(("127.0.0.1", port)) == 0
    except Exception:
        return False

# ── Headless launcher ──────────────────────────────────────────────────────
def _write_headless_launcher():
    """
    Write ktox_headless_loki.py into the vendored Loki payload directory.
    Starts Loki's webapp + orchestrator without the Pager LCD display.
    Monkey-patches SharedData to redirect /mmc/ paths to ktox_loot/loki/.
    Monkey-patches Loki.is_wifi_connected for standard Linux interfaces.
    """
    code = f'''\
#!/usr/bin/env python3
# ktox_headless_loki.py
# Headless Loki launcher for KTOx — webapp + orchestrator, no LCD display.
# Auto-generated by ktox_loki.py — do not edit manually.

import sys, os, threading, signal, logging, time, subprocess

_dir = os.path.dirname(os.path.abspath(__file__))
_lib = os.path.join(_dir, 'lib')
if os.path.exists(_lib) and _lib not in sys.path:
    sys.path.insert(0, _lib)
if _dir not in sys.path:
    sys.path.insert(0, _dir)

os.environ['CRYPTOGRAPHY_OPENSSL_NO_LEGACY'] = '1'

# ── Redirect Pager /mmc/ paths to KTOx loot directory before any import ───
_DATA = os.environ.get('LOKI_DATA_DIR', '{LOKI_DATA_DIR}')

from shared import SharedData as _SD
_orig_init = _SD.__init__

def _patched_init(self, *a, **kw):
    _orig_init(self, *a, **kw)
    self.datadir             = _DATA
    self.logsdir             = os.path.join(_DATA, 'logs')
    self.output_dir          = os.path.join(_DATA, 'output')
    self.input_dir           = os.path.join(_DATA, 'input')
    self.crackedpwddir       = os.path.join(_DATA, 'output', 'crackedpwd')
    self.datastolendir       = os.path.join(_DATA, 'output', 'datastolen')
    self.zombiesdir          = os.path.join(_DATA, 'output', 'zombies')
    self.vulnerabilities_dir = os.path.join(_DATA, 'output', 'vulnerabilities')
    self.scan_results_dir    = os.path.join(_DATA, 'output', 'vulnerabilities')
    self.netkbfile           = os.path.join(_DATA, 'netkb.csv')
    for d in [self.datadir, self.logsdir, self.output_dir, self.input_dir,
              self.crackedpwddir, self.datastolendir, self.zombiesdir,
              self.vulnerabilities_dir]:
        os.makedirs(d, exist_ok=True)

_SD.__init__ = _patched_init

# ── Patch Loki.is_wifi_connected for standard Linux (no wlan0cli needed) ──
import Loki as _loki_mod

def _ktox_wifi_check(self):
    """Check default route instead of Pager-specific wlan0cli interface."""
    try:
        r = subprocess.run(
            ['ip', 'route', 'show', 'default'],
            capture_output=True, text=True, timeout=5
        )
        self.wifi_connected = bool(r.stdout.strip())
    except Exception:
        self.wifi_connected = True
    return self.wifi_connected

_loki_mod.Loki.is_wifi_connected = _ktox_wifi_check

# ── Bring up Loki ──────────────────────────────────────────────────────────
from init_shared import shared_data
from Loki import Loki, handle_exit
from webapp import web_thread, handle_exit_web
from logger import Logger

logger = Logger(name='ktox_headless_loki', level=logging.INFO)

if __name__ == '__main__':
    shared_data.load_config()

    bjorn_ip = os.environ.get('BJORN_IP', '')
    if bjorn_ip:
        os.environ['BJORN_IP'] = bjorn_ip
        logger.info(f'Target network IP: {{bjorn_ip}}')

    pid_file = os.environ.get('LOKI_PID_FILE', '')
    if pid_file:
        with open(pid_file, 'w') as _pf:
            _pf.write(str(os.getpid()))

    # Start web server (Loki dashboard at :8000)
    shared_data.webapp_should_exit = False
    shared_data.display_should_exit = True   # no LCD
    web_thread.start()
    logger.info('Loki web interface started on port 8000')

    # Start Loki main loop (spawns Orchestrator once network is up)
    loki = Loki(shared_data)
    shared_data.loki_instance = loki
    loki_thread = threading.Thread(target=loki.run, daemon=True)
    loki_thread.start()

    signal.signal(signal.SIGINT,
                  lambda s, f: handle_exit(s, f, loki_thread, loki_thread, web_thread))
    signal.signal(signal.SIGTERM,
                  lambda s, f: handle_exit(s, f, loki_thread, loki_thread, web_thread))

    logger.info(f'Loki running — open http://0.0.0.0:8000 in your browser')

    while not shared_data.should_exit:
        time.sleep(2)
'''
    LOKI_LAUNCHER.write_text(code)
    LOKI_LAUNCHER.chmod(0o755)


# ── Install ────────────────────────────────────────────────────────────────
def install_loki() -> bool:
    section("Loki Installation")

    # Clone repo
    if not VENDOR_DIR.exists() or not (VENDOR_DIR / ".git").exists():
        info(f"Cloning {LOKI_REPO_URL} ...")
        VENDOR_DIR.parent.mkdir(parents=True, exist_ok=True)
        if VENDOR_DIR.exists():
            shutil.rmtree(VENDOR_DIR)
        r = subprocess.run(
            ["git", "clone", "--depth=1", LOKI_REPO_URL, str(VENDOR_DIR)],
            capture_output=True, text=True
        )
        if r.returncode != 0:
            err(f"Clone failed:\n{r.stderr.strip()}")
            return False
        ok("Repository cloned.")
    else:
        ok("Repository already present.")

    # Ensure nmap is available (Loki's vuln scanner needs it)
    if not shutil.which("nmap"):
        info("Installing nmap...")
        subprocess.run(["apt-get", "install", "-y", "nmap"], capture_output=True)

    # Write headless launcher into vendored directory
    _write_headless_launcher()
    ok("Headless launcher written.")

    # Create persistent data directories
    for sub in ["logs", "output/crackedpwd", "output/datastolen",
                "output/zombies", "output/vulnerabilities", "input"]:
        (LOKI_DATA_DIR / sub).mkdir(parents=True, exist_ok=True)
    ok(f"Data directory ready: {LOKI_DATA_DIR}")

    console.print()
    ok("[bold]Loki installed successfully.[/bold]")
    local_ip = _get_local_ip()
    info(f"Start with [ST], then open  http://{local_ip}:{LOKI_PORT}  in your browser.")
    return True


def update_loki() -> bool:
    section("Updating Loki")
    if not VENDOR_DIR.exists():
        err("Loki not installed. Run [IN] Install first.")
        return False
    r = subprocess.run(
        ["git", "-C", str(VENDOR_DIR), "pull"],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        err(f"Update failed:\n{r.stderr.strip()}")
        return False
    _write_headless_launcher()
    ok("Loki updated and headless launcher refreshed.")
    return True


# ── Process management ─────────────────────────────────────────────────────
def start_loki() -> bool:
    global _loki_proc

    if _loki_running():
        local_ip = _get_local_ip()
        warn("Loki is already running.")
        info(f"Web UI: http://{local_ip}:{LOKI_PORT}")
        return False

    if not _loki_installed():
        err("Loki not installed. Choose [IN] to install first.")
        return False

    if _port_in_use(LOKI_PORT):
        err(f"Port {LOKI_PORT} is already in use by another process.")
        return False

    local_ip = _get_local_ip()
    env = os.environ.copy()
    env["LOKI_DATA_DIR"] = str(LOKI_DATA_DIR)
    env["BJORN_IP"]      = local_ip
    env["LOKI_PID_FILE"] = str(LOKI_PID_FILE)

    log_path = LOKI_DATA_DIR / "logs" / "ktox_loki_stdout.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_fh = open(log_path, "a")

    with _proc_lock:
        _loki_proc = subprocess.Popen(
            [sys.executable, str(LOKI_LAUNCHER)],
            env=env,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            cwd=str(LOKI_DIR),
        )

    # Brief wait to confirm process is alive
    time.sleep(3)
    if not _loki_running():
        err("Loki process exited immediately — check logs with [LG].")
        return False

    ok(f"Loki started  (PID {_loki_proc.pid})")
    ok(f"Web UI →  http://{local_ip}:{LOKI_PORT}")
    ok(f"Stdout log: {log_path}")
    return True


def stop_loki() -> bool:
    global _loki_proc

    if not _loki_running():
        warn("Loki is not running.")
        return False

    with _proc_lock:
        if _loki_proc is not None:
            try:
                _loki_proc.terminate()
                _loki_proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                _loki_proc.kill()
            _loki_proc = None

        if LOKI_PID_FILE.exists():
            try:
                pid = int(LOKI_PID_FILE.read_text().strip())
                os.kill(pid, signal.SIGTERM)
                time.sleep(2)
                try:
                    os.kill(pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
            except (ValueError, ProcessLookupError):
                pass
            LOKI_PID_FILE.unlink(missing_ok=True)

    # Kill any orphaned nmap processes Loki may have left
    subprocess.run(["killall", "-q", "nmap"], capture_output=True)

    ok("Loki stopped.")
    return True


# ── Status panel ───────────────────────────────────────────────────────────
def _draw_status():
    running   = _loki_running()
    installed = _loki_installed()
    local_ip  = _get_local_ip()

    t = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    t.add_column(style=C_STEEL, no_wrap=True)
    t.add_column(style=C_ASH)

    inst_str   = f"[{C_GOOD}]Yes[/{C_GOOD}]"   if installed else f"[{C_BLOOD}]No — run [IN] Install[/{C_BLOOD}]"
    status_str = f"[{C_GOOD}]● RUNNING[/{C_GOOD}]" if running  else f"[{C_DIM}]○ STOPPED[/{C_DIM}]"
    web_str    = (f"[{C_EMBER}]http://{local_ip}:{LOKI_PORT}[/{C_EMBER}]"
                  if running
                  else f"[{C_DIM}]http://{local_ip}:{LOKI_PORT} (offline)[/{C_DIM}]")

    t.add_row("Installed", inst_str)
    t.add_row("Status",    status_str)
    t.add_row("Web UI",    web_str)
    t.add_row("Data dir",  str(LOKI_DATA_DIR))
    t.add_row("Source",    str(LOKI_DIR) if installed else "not cloned")

    if running and _loki_proc is not None:
        t.add_row("PID", str(_loki_proc.pid))

    console.print(Panel(
        t,
        title=f"[bold {C_BLOOD}]  Loki Autonomous Engine  [/bold {C_BLOOD}]",
        border_style=C_RUST, box=box.HEAVY
    ))


def _tail_logs(n: int = 40):
    log_path = LOKI_DATA_DIR / "logs" / "ktox_loki_stdout.log"
    if not log_path.exists():
        warn("No log file yet — start Loki first.")
        return
    lines = log_path.read_text(errors="replace").splitlines()
    console.print()
    console.print(Rule(f"[{C_STEEL}]Last {n} lines — {log_path.name}[/{C_STEEL}]", style=C_DIM))
    for line in lines[-n:]:
        console.print(f"  [{C_DIM}]{line}[/{C_DIM}]")
    console.print()


# ── Menu ───────────────────────────────────────────────────────────────────
_LOKI_MENU = [
    ("ST", "Start Loki"),
    ("SP", "Stop  Loki"),
    ("SS", "Status"),
    ("LG", "View Logs (last 40 lines)"),
    ("IN", "Install / Re-install"),
    ("UP", "Update (git pull)"),
    ("BK", "Back to KTOx menu"),
]

def loki_menu():
    while True:
        console.print()
        console.print(Rule(f"[bold {C_BLOOD}] LOKI AUTONOMOUS ENGINE [/bold {C_BLOOD}]", style=C_RUST))
        _draw_status()
        console.print()
        for key, label in _LOKI_MENU:
            console.print(f"  [{C_BLOOD}][{key}][/{C_BLOOD}]  [{C_ASH}]{label}[/{C_ASH}]")
        console.print()

        try:
            choice = Prompt.ask(f"  [{C_BLOOD}]loki[/{C_BLOOD}]").strip().upper()
        except (KeyboardInterrupt, EOFError):
            return

        if choice == "ST":
            if not _loki_installed():
                if Confirm.ask(f"  [{C_ORANGE}]Loki not installed. Install now?[/{C_ORANGE}]"):
                    if not install_loki():
                        continue
                else:
                    continue
            start_loki()

        elif choice == "SP":
            stop_loki()

        elif choice == "SS":
            _draw_status()

        elif choice == "LG":
            _tail_logs()

        elif choice == "IN":
            if _loki_running():
                warn("Stop Loki before re-installing.")
            else:
                install_loki()

        elif choice == "UP":
            if _loki_running():
                warn("Stop Loki before updating.")
            else:
                update_loki()

        elif choice == "BK":
            return

        else:
            err("Invalid option.")
